// Code generated by tygo. DO NOT EDIT.

//////////
// source: audit_event.go

export interface AuditEvent {
  id: string;
  tenant_id?: string;
  actor: string;
  action: string;
  target_id?: string;
  payload: string;
  created_at: string;
}

//////////
// source: client.go

export interface Client {
  id: string;
  tenant_id: string;
  name: string;
  folder_path: string;
  root_folder_id?: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: feed_event.go

export const FeedEventTypeFileUploaded = "file_uploaded";
export const FeedEventTypeInviteAccepted = "invite_accepted";
export const FeedEventSourceTypeFileActivity = "file_activity";
export const FeedEventSourceTypeFileUploadBatch = "file_upload_batch";
export const FeedEventSourceTypeInviteToken = "invite_token";
export const FeedStateUnread = "unread";
export const FeedStateRead = "read";
export const FeedStateAll = "all";
export interface FeedSummary {
  unread_count: number /* int64 */;
  read_count: number /* int64 */;
}
export interface FeedListResponse {
  pagination: PaginationResponse;
  items: FeedEvent[];
  summary: FeedSummary;
}
export interface FeedEventFile {
  id: string;
  path: string;
}
export interface FeedEvent {
  id: string;
  tenant_id: string;
  user_id: string;
  event_type: string;
  client_id?: string;
  actor_user_id?: string;
  subject_user_id?: string;
  source_type: string;
  source_id: string;
  file_id?: string;
  file_path: string;
  created_at: string;
  client_name?: string;
  actor_name?: string;
  actor_email?: string;
  subject_name?: string;
  subject_email?: string;
  files?: FeedEventFile[];
  file_count?: number /* int */;
  is_read: boolean;
  read_at?: string;
}

//////////
// source: file.go

/**
 * File stores metadata for uploaded files
 */
export interface File {
  id: string;
  tenant_id: string;
  client_id: string;
  user_id?: string;
  folder_id?: string;
  filename: string;
  path: string;
  type: string;
  size: number /* int64 */;
  uploaded_at: string;
  deleted_at?: string;
  disk_deleted_at?: string;
}
/**
 * FileItem is used for TypeScript type generation
 * (hack to emit a type with the proper name that doesn't conflict with the native JS File type)
 */
export interface FileItem extends File {
}

//////////
// source: file_activity.go

export interface FileActivity {
  id: string;
  tenant_id: string;
  client_id: string;
  user_id?: string;
  secure_link_id?: string;
  file_id?: string;
  upload_batch_id?: string;
  action: string;
  file_path: string;
  created_at: string;
}

//////////
// source: invite_token.go

export interface InviteToken {
  id: string;
  tenant_id: string;
  user_id: string;
  email: string;
  token_hash: string;
  expires_at: string;
  used_at?: string;
  invited_by: string;
  created_at: string;
}

//////////
// source: passkey.go

/**
 * PasskeyCredential stores the credential record required to validate a WebAuthn assertion.
 * CredentialData is intentionally never exposed through the API.
 */
export interface PasskeyCredential {
  id: string;
  tenant_id: string;
  user_id: string;
  name: string;
  created_at: string;
  last_used_at?: string;
}
/**
 * WebAuthnChallenge persists server-side ceremony state. Challenge data is never sent back to clients.
 */
export interface WebAuthnChallenge {
  id: string;
  tenant_id: string;
  user_id: string;
  purpose: string;
  expires_at: string;
  used_at?: string;
  created_at: string;
}

//////////
// source: queued_email.go

export interface QueuedEmail {
  id: string;
  tenant_id: string;
  recipient: string;
  subject: string;
  body: string;
  html_body: string;
  file_ids_csv: string;
  client_id?: string;
  event_type: string;
  scheduled_for: string;
  sent_at?: string;
  created_at: string;
}

//////////
// source: secure_link.go

export interface SecureLink {
  id: string;
  tenant_id: string;
  client_id: string;
  token: string;
  link_url?: string;
  email: string;
  expires_at: string;
  access_type: string;
  created_by: string;
  created_at: string;
  last_accessed?: string;
}

//////////
// source: tenant.go

export interface Tenant {
  id: string;
  slug: string;
  name: string;
  created_at: string;
  updated_at: string;
}

//////////
// source: tenant_domain.go

export interface TenantDomain {
  id: string;
  tenant_id: string;
  domain: string;
  kind: string;
  is_primary: boolean;
  created_at: string;
  updated_at: string;
}

//////////
// source: tenant_entitlement.go

export interface TenantEntitlement {
  id: string;
  tenant_id: string;
  status: string;
  plan_code: string;
  max_users: number /* int64 */;
  max_storage_bytes: number /* int64 */;
  created_at: string;
  updated_at: string;
}

//////////
// source: tenant_settings.go

export interface TenantSettings {
  id: string;
  tenant_id: string;
  site_title: string;
  logo_path: string;
  primary_color: string;
  public_base_url: string;
  effective_public_base_url?: string;
  invite_welcome_text: string;
  secure_link_default_expiry_days: number /* int */;
  created_at: string;
  updated_at: string;
}

//////////
// source: user.go

export interface User {
  id: string;
  tenant_id: string;
  email: string;
  role: string;
  name: string;
  is_initial_admin?: boolean;
  client_ids?: string[];
  invite_accepted: boolean;
  created_at: string;
  updated_at: string;
}

//////////
// source: user_client.go

/**
 * UserClient maps users to the clients they are allowed to access.
 */
export interface UserClient {
  tenant_id: string;
  user_id: string;
  client_id: string;
  created_at: string;
}

//////////
// source: util.go

/**
 * PaginationResponse represents pagination metadata
 */
export interface PaginationResponse {
  total_items: number /* int64 */;
  total_pages: number /* int */;
  page: number /* int */;
  page_size: number /* int */;
  has_more: boolean;
  items_per_page: number /* int */;
}
/**
 * PaginatedResult represents a paginated list of items
 */
export interface PaginatedResult<T extends any> {
  pagination: PaginationResponse;
  items: T[];
}
