package configschema

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math/big"
	"os"
	"reflect"
	"sort"
	"strings"

	reflectschema "github.com/invopop/jsonschema"
	validateschema "github.com/santhosh-tekuri/jsonschema/v6"
	"go.yaml.in/yaml/v3"
	"golang.org/x/text/language"
	"golang.org/x/text/message"
)

const (
	Draft           = "https://json-schema.org/draft/2020-12/schema"
	SinceAnnotation = "x-since"
)

var ErrInvalid = errors.New("configuration is invalid")

type options struct {
	fieldNameTag string
	defaults     map[string]any
}

// Option customizes schema generation and validation.
type Option func(*options)

// WithFieldNameTag selects the struct tag that contains configuration field names.
func WithFieldNameTag(tag string) Option {
	return func(opts *options) {
		opts.fieldNameTag = tag
	}
}

// WithDefaults adds JSON Schema defaults for dot-separated configuration paths.
func WithDefaults(defaults map[string]any) Option {
	return func(opts *options) {
		opts.defaults = make(map[string]any, len(defaults))
		for path, value := range defaults {
			opts.defaults[path] = value
		}
	}
}

// ValidationIssue describes one value that does not match the generated schema.
type ValidationIssue struct {
	Path    string
	Message string
}

// Report compares a configuration document with the schema generated by a Go type.
type Report struct {
	Filename        string
	SchemaName      string
	SchemaVersion   string
	MissingRequired []string
	MissingOptional []string
	// MissingOptionalDefaults contains the configured defaults for absent optional fields.
	MissingOptionalDefaults map[string]any
	// MissingFieldSince contains SinceAnnotation values for absent fields.
	MissingFieldSince map[string]string
	Issues            []ValidationIssue
}

// Valid reports whether the document satisfies the generated schema. Missing optional
// fields are informational and do not make a document invalid.
func (r Report) Valid() bool {
	return len(r.MissingRequired) == 0 && len(r.Issues) == 0
}

// MarkRequired promotes a missing optional field, or its missing parent, to a
// required field while preserving any metadata attached to the requested path.
func (r *Report) MarkRequired(path string) {
	if path == "" {
		return
	}

	found := false
	for _, required := range r.MissingRequired {
		if required == path {
			found = true
			break
		}
	}
	if !found {
		r.MissingRequired = append(r.MissingRequired, path)
		sort.Strings(r.MissingRequired)
	}

	optional := r.MissingOptional[:0]
	for _, missing := range r.MissingOptional {
		if missing == path || strings.HasPrefix(path, missing+".") {
			delete(r.MissingOptionalDefaults, missing)
			if missing != path {
				delete(r.MissingFieldSince, missing)
			}
			continue
		}
		optional = append(optional, missing)
	}
	r.MissingOptional = optional
}

// MarkRequiredIfBlank marks path as required when value is empty or contains
// only whitespace. It reports whether the value was blank.
func (r *Report) MarkRequiredIfBlank(path, value string) bool {
	if strings.TrimSpace(value) != "" {
		return false
	}
	r.MarkRequired(path)
	return true
}

// Err returns ErrInvalid when the report contains schema validation failures.
func (r Report) Err() error {
	if r.Valid() {
		return nil
	}

	var details []string
	if len(r.MissingRequired) > 0 {
		details = append(details, "missing required fields: "+strings.Join(r.MissingRequired, ", "))
	}
	for _, issue := range r.Issues {
		details = append(details, issue.Path+": "+issue.Message)
	}
	return fmt.Errorf("%w: %s", ErrInvalid, strings.Join(details, "; "))
}

// Generate produces a JSON Schema Draft 2020-12 document for value's Go type.
// Fields are optional unless explicitly tagged jsonschema:"required".
func Generate(value any, optionValues ...Option) ([]byte, error) {
	opts := resolveOptions(optionValues)
	if err := validateType(value); err != nil {
		return nil, err
	}

	reflector := &reflectschema.Reflector{
		Anonymous:                  true,
		DoNotReference:             true,
		ExpandedStruct:             true,
		RequiredFromJSONSchemaTags: true,
		FieldNameTag:               opts.fieldNameTag,
		AllowAdditionalProperties:  false,
		Mapper:                     boundedIntegerSchema,
	}
	schema := reflector.Reflect(value)
	data, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal generated schema: %w", err)
	}
	if len(opts.defaults) > 0 {
		var document map[string]any
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.UseNumber()
		if err := decoder.Decode(&document); err != nil {
			return nil, fmt.Errorf("decode generated schema: %w", err)
		}
		if err := applyDefaults(document, opts.defaults); err != nil {
			return nil, err
		}
		data, err = json.MarshalIndent(document, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("marshal generated schema with defaults: %w", err)
		}
	}
	return append(data, '\n'), nil
}

// ValidateYAMLFile validates a YAML file and reports fields absent from the file.
func ValidateYAMLFile(filename string, value any, optionValues ...Option) (Report, error) {
	documentData, err := os.ReadFile(filename)
	if err != nil {
		return Report{Filename: filename, SchemaName: schemaName(value)}, fmt.Errorf("read configuration file %q: %w", filename, err)
	}
	return ValidateYAML(filename, documentData, value, optionValues...)
}

// ValidateYAML validates a YAML byte snapshot and reports fields absent from it.
func ValidateYAML(filename string, documentData []byte, value any, optionValues ...Option) (Report, error) {
	report := Report{Filename: filename, SchemaName: schemaName(value)}
	schemaData, err := Generate(value, optionValues...)
	if err != nil {
		return report, err
	}
	report.SchemaVersion = version(schemaData)

	var yamlDocument any
	decoder := yaml.NewDecoder(bytes.NewReader(documentData))
	if err := decoder.Decode(&yamlDocument); err != nil && err != io.EOF {
		return report, fmt.Errorf("parse configuration file %q: %w", filename, err)
	}
	if yamlDocument == nil && commentsOnly(documentData) {
		yamlDocument = map[string]any{}
	}
	var extraDocument any
	if err := decoder.Decode(&extraDocument); err != io.EOF {
		if err == nil {
			return report, fmt.Errorf("parse configuration file %q: multiple YAML documents are not supported", filename)
		}
		return report, fmt.Errorf("parse configuration file %q: %w", filename, err)
	}

	jsonDocument, err := json.Marshal(yamlDocument)
	if err != nil {
		return report, fmt.Errorf("convert configuration file %q to JSON: %w", filename, err)
	}
	instance, err := validateschema.UnmarshalJSON(bytes.NewReader(jsonDocument))
	if err != nil {
		return report, fmt.Errorf("decode configuration file %q as JSON: %w", filename, err)
	}

	if document, ok := instance.(map[string]any); ok {
		var generatedSchema map[string]any
		if err := json.Unmarshal(schemaData, &generatedSchema); err != nil {
			return report, fmt.Errorf("decode generated schema: %w", err)
		}
		collectMissing(generatedSchema, document, "", &report)
	}

	validationErr, err := validate(schemaData, instance)
	if err != nil {
		return report, err
	}
	if validationErr != nil {
		collectValidationIssues(validationErr, &report.Issues)
	}

	sort.Strings(report.MissingRequired)
	sort.Strings(report.MissingOptional)
	sort.Slice(report.Issues, func(i, j int) bool {
		if report.Issues[i].Path == report.Issues[j].Path {
			return report.Issues[i].Message < report.Issues[j].Message
		}
		return report.Issues[i].Path < report.Issues[j].Path
	})
	return report, nil
}

// WriteReport writes a human-readable validation summary.
func WriteReport(w io.Writer, report Report) error {
	status := "valid"
	if !report.Valid() {
		status = "invalid"
	}

	if _, err := fmt.Fprintf(w, "Config file: %s\nSchema: %s\nSchema version: %s\nJSON Schema: %s\nStatus: %s\n", report.Filename, report.SchemaName, report.SchemaVersion, Draft, status); err != nil {
		return err
	}
	if err := writeFields(w, "Missing required fields", report.MissingRequired, report.MissingFieldSince); err != nil {
		return err
	}
	if err := writeOptionalFields(w, report.MissingOptional, report.MissingOptionalDefaults, report.MissingFieldSince); err != nil {
		return err
	}
	if len(report.Issues) > 0 {
		if _, err := fmt.Fprintf(w, "Validation errors (%d):\n", len(report.Issues)); err != nil {
			return err
		}
		for _, issue := range report.Issues {
			if _, err := fmt.Fprintf(w, "- %s: %s\n", issue.Path, issue.Message); err != nil {
				return err
			}
		}
	}
	return nil
}

func resolveOptions(optionValues []Option) options {
	opts := options{fieldNameTag: "json"}
	for _, optionValue := range optionValues {
		optionValue(&opts)
	}
	return opts
}

func applyDefaults(schema map[string]any, defaults map[string]any) error {
	paths := make([]string, 0, len(defaults))
	for path := range defaults {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		property, err := schemaProperty(schema, path)
		if err != nil {
			return err
		}
		property["default"] = defaults[path]
	}
	return nil
}

func schemaProperty(schema map[string]any, path string) (map[string]any, error) {
	current := schema
	for _, name := range strings.Split(path, ".") {
		properties, ok := current["properties"].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("apply default for %q: schema has no properties", path)
		}
		property, ok := properties[name].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("apply default for %q: property does not exist", path)
		}
		current = property
	}
	return current, nil
}

func validateType(value any) error {
	if value == nil {
		return errors.New("configuration schema type cannot be nil")
	}
	typeOf := reflect.TypeOf(value)
	for typeOf.Kind() == reflect.Pointer {
		typeOf = typeOf.Elem()
	}
	if typeOf.Kind() != reflect.Struct {
		return fmt.Errorf("configuration schema type must be a struct, got %s", typeOf.Kind())
	}
	return nil
}

func schemaName(value any) string {
	if value == nil {
		return "unknown"
	}
	typeOf := reflect.TypeOf(value)
	for typeOf.Kind() == reflect.Pointer {
		typeOf = typeOf.Elem()
	}
	if typeOf.Name() == "" {
		return typeOf.String()
	}
	return typeOf.Name()
}

func version(schema []byte) string {
	digest := sha256.Sum256(schema)
	return fmt.Sprintf("sha256:%x", digest[:8])
}

func boundedIntegerSchema(typeOf reflect.Type) *reflectschema.Schema {
	kind := typeOf.Kind()
	if kind < reflect.Int || kind > reflect.Uintptr {
		return nil
	}

	bits := typeOf.Bits()
	one := big.NewInt(1)
	if kind >= reflect.Int && kind <= reflect.Int64 {
		limit := new(big.Int).Lsh(new(big.Int).Set(one), uint(bits-1))
		minimum := new(big.Int).Neg(new(big.Int).Set(limit))
		maximum := new(big.Int).Sub(new(big.Int).Set(limit), one)
		return &reflectschema.Schema{
			Type:    "integer",
			Minimum: json.Number(minimum.String()),
			Maximum: json.Number(maximum.String()),
		}
	}

	maximum := new(big.Int).Sub(new(big.Int).Lsh(new(big.Int).Set(one), uint(bits)), one)
	return &reflectschema.Schema{
		Type:    "integer",
		Minimum: json.Number("0"),
		Maximum: json.Number(maximum.String()),
	}
}

func commentsOnly(data []byte) bool {
	for _, line := range bytes.Split(data, []byte("\n")) {
		line = bytes.TrimSpace(line)
		if len(line) != 0 && line[0] != '#' {
			return false
		}
	}
	return true
}

func validate(schemaData []byte, instance any) (*validateschema.ValidationError, error) {
	schemaDocument, err := validateschema.UnmarshalJSON(bytes.NewReader(schemaData))
	if err != nil {
		return nil, fmt.Errorf("decode generated schema: %w", err)
	}
	compiler := validateschema.NewCompiler()
	if err := compiler.AddResource("config.schema.json", schemaDocument); err != nil {
		return nil, fmt.Errorf("add generated schema: %w", err)
	}
	compiled, err := compiler.Compile("config.schema.json")
	if err != nil {
		return nil, fmt.Errorf("compile generated schema: %w", err)
	}
	if err := compiled.Validate(instance); err != nil {
		var validationErr *validateschema.ValidationError
		if !errors.As(err, &validationErr) {
			return nil, fmt.Errorf("validate configuration: %w", err)
		}
		return validationErr, nil
	}
	return nil, nil
}

func collectMissing(schema map[string]any, document map[string]any, prefix string, report *Report) {
	properties, ok := schema["properties"].(map[string]any)
	if !ok {
		return
	}
	required := stringSet(schema["required"])
	keys := make([]string, 0, len(properties))
	for key := range properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	for _, key := range keys {
		path := joinPath(prefix, key)
		value, exists := document[key]
		if !exists {
			addSince(report, path, childSince(properties, key))
			if required[key] {
				report.MissingRequired = append(report.MissingRequired, path)
			} else {
				report.MissingOptional = append(report.MissingOptional, path)
				if defaultValue, hasDefault := childDefault(properties, key); hasDefault {
					if report.MissingOptionalDefaults == nil {
						report.MissingOptionalDefaults = make(map[string]any)
					}
					report.MissingOptionalDefaults[path] = defaultValue
				}
			}
			continue
		}
		childSchema, schemaOK := properties[key].(map[string]any)
		childDocument, documentOK := value.(map[string]any)
		if schemaOK && documentOK {
			collectMissing(childSchema, childDocument, path, report)
		}
	}
}

func childDefault(properties map[string]any, key string) (any, bool) {
	property, ok := properties[key].(map[string]any)
	if !ok {
		return nil, false
	}
	defaultValue, hasDefault := property["default"]
	return defaultValue, hasDefault
}

func childSince(properties map[string]any, key string) string {
	property, ok := properties[key].(map[string]any)
	if !ok {
		return ""
	}
	since, _ := property[SinceAnnotation].(string)
	return since
}

func addSince(report *Report, path, since string) {
	if since == "" {
		return
	}
	if report.MissingFieldSince == nil {
		report.MissingFieldSince = make(map[string]string)
	}
	report.MissingFieldSince[path] = since
}

func stringSet(value any) map[string]bool {
	set := make(map[string]bool)
	values, ok := value.([]any)
	if !ok {
		return set
	}
	for _, item := range values {
		if text, ok := item.(string); ok {
			set[text] = true
		}
	}
	return set
}

func collectValidationIssues(validationErr *validateschema.ValidationError, issues *[]ValidationIssue) {
	if len(validationErr.Causes) > 0 {
		for _, cause := range validationErr.Causes {
			collectValidationIssues(cause, issues)
		}
		return
	}
	keywordPath := validationErr.ErrorKind.KeywordPath()
	if len(keywordPath) > 0 && keywordPath[len(keywordPath)-1] == "required" {
		return
	}
	printer := message.NewPrinter(language.English)
	*issues = append(*issues, ValidationIssue{
		Path:    instancePath(validationErr.InstanceLocation),
		Message: validationErr.ErrorKind.LocalizedString(printer),
	})
}

func instancePath(parts []string) string {
	if len(parts) == 0 {
		return "$"
	}
	return strings.Join(parts, ".")
}

func joinPath(prefix, name string) string {
	if prefix == "" {
		return name
	}
	return prefix + "." + name
}

func writeFields(w io.Writer, label string, fields []string, sinceValues map[string]string) error {
	if len(fields) == 0 {
		return nil
	}
	if _, err := fmt.Fprintf(w, "%s (%d):\n", label, len(fields)); err != nil {
		return err
	}
	for _, field := range fields {
		if err := writeMissingField(w, field, nil, false, sinceValues[field]); err != nil {
			return err
		}
	}
	return nil
}

func writeOptionalFields(w io.Writer, fields []string, defaults map[string]any, sinceValues map[string]string) error {
	if len(fields) == 0 {
		return nil
	}
	if _, err := fmt.Fprintf(w, "Missing optional fields (%d):\n", len(fields)); err != nil {
		return err
	}
	for _, field := range fields {
		defaultValue, hasDefault := defaults[field]
		if err := writeMissingField(w, field, defaultValue, hasDefault, sinceValues[field]); err != nil {
			return err
		}
	}
	return nil
}

func writeMissingField(w io.Writer, field string, defaultValue any, hasDefault bool, since string) error {
	annotations := make([]string, 0, 2)
	if hasDefault {
		formattedDefault, err := json.Marshal(defaultValue)
		if err != nil {
			return fmt.Errorf("format default for %q: %w", field, err)
		}
		annotations = append(annotations, "default: "+string(formattedDefault))
	}
	if since != "" {
		annotations = append(annotations, "since: "+since)
	}
	if len(annotations) == 0 {
		_, err := fmt.Fprintf(w, "- %s\n", field)
		return err
	}
	_, err := fmt.Fprintf(w, "- %s (%s)\n", field, strings.Join(annotations, "; "))
	return err
}
