// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var AuditEvent = struct {
	ID        field.String
	TenantID  field.String
	Actor     field.String
	Action    field.String
	TargetID  field.String
	Payload   field.String
	CreatedAt field.Time
}{
	ID:        field.String{}.WithColumn("id"),
	TenantID:  field.String{}.WithColumn("tenant_id"),
	Actor:     field.String{}.WithColumn("actor"),
	Action:    field.String{}.WithColumn("action"),
	TargetID:  field.String{}.WithColumn("target_id"),
	Payload:   field.String{}.WithColumn("payload"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
}
