// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var Client = struct {
	ID           field.String
	TenantID     field.String
	Name         field.String
	FolderPath   field.String
	RootFolderID field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time
}{
	ID:           field.String{}.WithColumn("id"),
	TenantID:     field.String{}.WithColumn("tenant_id"),
	Name:         field.String{}.WithColumn("name"),
	FolderPath:   field.String{}.WithColumn("folder_path"),
	RootFolderID: field.String{}.WithColumn("root_folder_id"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	UpdatedAt:    field.Time{}.WithColumn("updated_at"),
}
