// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"github.com/pixelcop/clientshare/internal/models"
	"gorm.io/cli/gorm/field"
)

var FeedSummary = struct {
	UnreadCount field.Number[int64]
	ReadCount   field.Number[int64]
}{
	UnreadCount: field.Number[int64]{}.WithColumn("unread_count"),
	ReadCount:   field.Number[int64]{}.WithColumn("read_count"),
}

var FeedListResponse = struct {
	Pagination field.Struct[models.PaginationResponse]
	Items      field.Slice[models.FeedEvent]
	Summary    field.Struct[models.FeedSummary]
}{
	Pagination: field.Struct[models.PaginationResponse]{}.WithName("Pagination"),
	Items:      field.Slice[models.FeedEvent]{}.WithName("Items"),
	Summary:    field.Struct[models.FeedSummary]{}.WithName("Summary"),
}

var FeedEventFile = struct {
	ID   field.String
	Path field.String
}{
	ID:   field.String{}.WithColumn("id"),
	Path: field.String{}.WithColumn("path"),
}

var FeedEvent = struct {
	ID            field.String
	TenantID      field.String
	UserID        field.String
	EventType     field.String
	ClientID      field.String
	ActorUserID   field.String
	SubjectUserID field.String
	SourceType    field.String
	SourceID      field.String
	FileID        field.String
	FilePath      field.String
	CreatedAt     field.Time
	ClientName    field.String
	ActorName     field.String
	ActorEmail    field.String
	SubjectName   field.String
	SubjectEmail  field.String
	Files         field.Slice[models.FeedEventFile]
	FileCount     field.Number[int]
	IsRead        field.Bool
	ReadAt        field.Time
}{
	ID:            field.String{}.WithColumn("id"),
	TenantID:      field.String{}.WithColumn("tenant_id"),
	UserID:        field.String{}.WithColumn("user_id"),
	EventType:     field.String{}.WithColumn("event_type"),
	ClientID:      field.String{}.WithColumn("client_id"),
	ActorUserID:   field.String{}.WithColumn("actor_user_id"),
	SubjectUserID: field.String{}.WithColumn("subject_user_id"),
	SourceType:    field.String{}.WithColumn("source_type"),
	SourceID:      field.String{}.WithColumn("source_id"),
	FileID:        field.String{}.WithColumn("file_id"),
	FilePath:      field.String{}.WithColumn("file_path"),
	CreatedAt:     field.Time{}.WithColumn("created_at"),
	ClientName:    field.String{}.WithColumn("client_name"),
	ActorName:     field.String{}.WithColumn("actor_name"),
	ActorEmail:    field.String{}.WithColumn("actor_email"),
	SubjectName:   field.String{}.WithColumn("subject_name"),
	SubjectEmail:  field.String{}.WithColumn("subject_email"),
	Files:         field.Slice[models.FeedEventFile]{}.WithName("Files"),
	FileCount:     field.Number[int]{}.WithColumn("file_count"),
	IsRead:        field.Bool{}.WithColumn("is_read"),
	ReadAt:        field.Time{}.WithColumn("read_at"),
}
