// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var FileActivity = struct {
	ID            field.String
	TenantID      field.String
	ClientID      field.String
	UserID        field.String
	SecureLinkID  field.String
	FileID        field.String
	UploadBatchID field.String
	Action        field.String
	FilePath      field.String
	CreatedAt     field.Time
}{
	ID:            field.String{}.WithColumn("id"),
	TenantID:      field.String{}.WithColumn("tenant_id"),
	ClientID:      field.String{}.WithColumn("client_id"),
	UserID:        field.String{}.WithColumn("user_id"),
	SecureLinkID:  field.String{}.WithColumn("secure_link_id"),
	FileID:        field.String{}.WithColumn("file_id"),
	UploadBatchID: field.String{}.WithColumn("upload_batch_id"),
	Action:        field.String{}.WithColumn("action"),
	FilePath:      field.String{}.WithColumn("file_path"),
	CreatedAt:     field.Time{}.WithColumn("created_at"),
}
