// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var PasskeySignup = struct {
	ID             field.String
	TokenHash      field.String
	Email          field.String
	TenantSlug     field.String
	UserID         field.String
	SessionData    field.Bytes
	CredentialData field.Bytes
	RPID           field.String
	ExpiresAt      field.Time
	VerifiedAt     field.Time
	Reserved       field.Bool
	TenantID       field.String
}{
	ID:             field.String{}.WithColumn("id"),
	TokenHash:      field.String{}.WithColumn("token_hash"),
	Email:          field.String{}.WithColumn("email"),
	TenantSlug:     field.String{}.WithColumn("tenant_slug"),
	UserID:         field.String{}.WithColumn("user_id"),
	SessionData:    field.Bytes{}.WithColumn("session_data"),
	CredentialData: field.Bytes{}.WithColumn("credential_data"),
	RPID:           field.String{}.WithColumn("rp_id"),
	ExpiresAt:      field.Time{}.WithColumn("expires_at"),
	VerifiedAt:     field.Time{}.WithColumn("verified_at"),
	Reserved:       field.Bool{}.WithColumn("reserved"),
	TenantID:       field.String{}.WithColumn("tenant_id"),
}
