// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var PasskeyCredential = struct {
	ID               field.String
	TenantID         field.String
	UserID           field.String
	CredentialID     field.String
	CredentialIDHash field.String
	CredentialData   field.Bytes
	Name             field.String
	CreatedAt        field.Time
	LastUsedAt       field.Time
}{
	ID:               field.String{}.WithColumn("id"),
	TenantID:         field.String{}.WithColumn("tenant_id"),
	UserID:           field.String{}.WithColumn("user_id"),
	CredentialID:     field.String{}.WithColumn("credential_id"),
	CredentialIDHash: field.String{}.WithColumn("credential_id_hash"),
	CredentialData:   field.Bytes{}.WithColumn("credential_data"),
	Name:             field.String{}.WithColumn("name"),
	CreatedAt:        field.Time{}.WithColumn("created_at"),
	LastUsedAt:       field.Time{}.WithColumn("last_used_at"),
}

var WebAuthnChallenge = struct {
	ID          field.String
	TenantID    field.String
	UserID      field.String
	Purpose     field.String
	SessionData field.Bytes
	ExpiresAt   field.Time
	UsedAt      field.Time
	CreatedAt   field.Time
}{
	ID:          field.String{}.WithColumn("id"),
	TenantID:    field.String{}.WithColumn("tenant_id"),
	UserID:      field.String{}.WithColumn("user_id"),
	Purpose:     field.String{}.WithColumn("purpose"),
	SessionData: field.Bytes{}.WithColumn("session_data"),
	ExpiresAt:   field.Time{}.WithColumn("expires_at"),
	UsedAt:      field.Time{}.WithColumn("used_at"),
	CreatedAt:   field.Time{}.WithColumn("created_at"),
}
