// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var QueuedEmail = struct {
	ID           field.String
	TenantID     field.String
	Recipient    field.String
	Subject      field.String
	Body         field.String
	HTMLBody     field.String
	FileIDsCSV   field.String
	ClientID     field.String
	EventType    field.String
	ScheduledFor field.Time
	SentAt       field.Time
	CreatedAt    field.Time
}{
	ID:           field.String{}.WithColumn("id"),
	TenantID:     field.String{}.WithColumn("tenant_id"),
	Recipient:    field.String{}.WithColumn("recipient"),
	Subject:      field.String{}.WithColumn("subject"),
	Body:         field.String{}.WithColumn("body"),
	HTMLBody:     field.String{}.WithColumn("html_body"),
	FileIDsCSV:   field.String{}.WithColumn("file_ids_csv"),
	ClientID:     field.String{}.WithColumn("client_id"),
	EventType:    field.String{}.WithColumn("event_type"),
	ScheduledFor: field.Time{}.WithColumn("scheduled_for"),
	SentAt:       field.Time{}.WithColumn("sent_at"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
}
