// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var SecureLink = struct {
	ID           field.String
	TenantID     field.String
	ClientID     field.String
	Token        field.String
	LinkURL      field.String
	Email        field.String
	ExpiresAt    field.Time
	AccessType   field.String
	CreatedBy    field.String
	CreatedAt    field.Time
	LastAccessed field.Time
}{
	ID:           field.String{}.WithColumn("id"),
	TenantID:     field.String{}.WithColumn("tenant_id"),
	ClientID:     field.String{}.WithColumn("client_id"),
	Token:        field.String{}.WithColumn("token"),
	LinkURL:      field.String{}.WithColumn("link_url"),
	Email:        field.String{}.WithColumn("email"),
	ExpiresAt:    field.Time{}.WithColumn("expires_at"),
	AccessType:   field.String{}.WithColumn("access_type"),
	CreatedBy:    field.String{}.WithColumn("created_by"),
	CreatedAt:    field.Time{}.WithColumn("created_at"),
	LastAccessed: field.Time{}.WithColumn("last_accessed"),
}
