// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var TenantEntitlement = struct {
	ID              field.String
	TenantID        field.String
	Status          field.String
	PlanCode        field.String
	MaxUsers        field.Number[int64]
	MaxStorageBytes field.Number[int64]
	CreatedAt       field.Time
	UpdatedAt       field.Time
}{
	ID:              field.String{}.WithColumn("id"),
	TenantID:        field.String{}.WithColumn("tenant_id"),
	Status:          field.String{}.WithColumn("status"),
	PlanCode:        field.String{}.WithColumn("plan_code"),
	MaxUsers:        field.Number[int64]{}.WithColumn("max_users"),
	MaxStorageBytes: field.Number[int64]{}.WithColumn("max_storage_bytes"),
	CreatedAt:       field.Time{}.WithColumn("created_at"),
	UpdatedAt:       field.Time{}.WithColumn("updated_at"),
}
