// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var TenantSettings = struct {
	ID                          field.String
	TenantID                    field.String
	SiteTitle                   field.String
	LogoPath                    field.String
	PrimaryColor                field.String
	PublicBaseURL               field.String
	EffectivePublicBaseURL      field.String
	InviteWelcomeText           field.String
	SecureLinkDefaultExpiryDays field.Number[int]
	CreatedAt                   field.Time
	UpdatedAt                   field.Time
}{
	ID:                          field.String{}.WithColumn("id"),
	TenantID:                    field.String{}.WithColumn("tenant_id"),
	SiteTitle:                   field.String{}.WithColumn("site_title"),
	LogoPath:                    field.String{}.WithColumn("logo_path"),
	PrimaryColor:                field.String{}.WithColumn("primary_color"),
	PublicBaseURL:               field.String{}.WithColumn("public_base_url"),
	EffectivePublicBaseURL:      field.String{}.WithColumn("effective_public_base_url"),
	InviteWelcomeText:           field.String{}.WithColumn("invite_welcome_text"),
	SecureLinkDefaultExpiryDays: field.Number[int]{}.WithColumn("secure_link_default_expiry_days"),
	CreatedAt:                   field.Time{}.WithColumn("created_at"),
	UpdatedAt:                   field.Time{}.WithColumn("updated_at"),
}
