// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var Tenant = struct {
	ID        field.String
	Slug      field.String
	Name      field.String
	CreatedAt field.Time
	UpdatedAt field.Time
}{
	ID:        field.String{}.WithColumn("id"),
	Slug:      field.String{}.WithColumn("slug"),
	Name:      field.String{}.WithColumn("name"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
}
