// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	ID                     field.String
	TenantID               field.String
	Email                  field.String
	PasswordHash           field.String
	Role                   field.String
	Name                   field.String
	ClientIDs              field.Slice[string]
	InviteAccepted         field.Bool
	PasskeyPromptDismissed field.Bool
	CreatedAt              field.Time
	UpdatedAt              field.Time
}{
	ID:                     field.String{}.WithColumn("id"),
	TenantID:               field.String{}.WithColumn("tenant_id"),
	Email:                  field.String{}.WithColumn("email"),
	PasswordHash:           field.String{}.WithColumn("password_hash"),
	Role:                   field.String{}.WithColumn("role"),
	Name:                   field.String{}.WithColumn("name"),
	ClientIDs:              field.Slice[string]{}.WithName("ClientIDs"),
	InviteAccepted:         field.Bool{}.WithColumn("invite_accepted"),
	PasskeyPromptDismissed: field.Bool{}.WithColumn("passkey_prompt_dismissed"),
	CreatedAt:              field.Time{}.WithColumn("created_at"),
	UpdatedAt:              field.Time{}.WithColumn("updated_at"),
}
