// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package db

import (
	"gorm.io/cli/gorm/field"
)

var UserClient = struct {
	TenantID  field.String
	UserID    field.String
	ClientID  field.String
	CreatedAt field.Time
}{
	TenantID:  field.String{}.WithColumn("tenant_id"),
	UserID:    field.String{}.WithColumn("user_id"),
	ClientID:  field.String{}.WithColumn("client_id"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
}
